import { z } from "zod";
import { AUDIT_SEVERITY } from "./common";

export const AUTH_ACTIONS = z.enum([
  "SIGN_IN",
  "SIGN_OUT",
  "SIGN_UP",
  "PASSWORD_CHANGE",
  "PASSWORD_RESET_REQUEST",
  "PASSWORD_RESET_COMPLETE",
  "EMAIL_VERIFY_REQUEST",
  "EMAIL_VERIFY_COMPLETE",
  "PHONE_VERIFY_REQUEST",
  "PHONE_VERIFY_COMPLETE",
  "TWO_FACTOR_ENABLE",
  "TWO_FACTOR_DISABLE",
  "TWO_FACTOR_CHALLENGE",
  "TWO_FACTOR_VERIFY",
  "BACKUP_CODE_USED",
  "PASSKEY_REGISTER",
  "PASSKEY_REMOVE",
  "PASSKEY_AUTHENTICATE",
  "SESSION_CREATE",
  "SESSION_REFRESH",
  "SESSION_REVOKE",
  "SESSION_REVOKE_ALL",
  "DEVICE_TRUST",
  "DEVICE_UNTRUST",
  "DEVICE_REVOKE",
  "IMPERSONATION_START",
  "IMPERSONATION_END",
  "ACCOUNT_BAN",
  "ACCOUNT_UNBAN",
  "ACCOUNT_DELETE",
  "ROLE_CHANGE",
  "ORG_JOIN",
  "ORG_LEAVE",
  "ORG_INVITE_ACCEPT",
  "ORG_INVITE_DECLINE",
  "DEVICE_AUTH_REQUEST",
  "DEVICE_AUTH_APPROVE",
  "DEVICE_AUTH_REJECT",
  "COMPROMISED_PASSWORD_DETECTED",
  "RATE_LIMITED",
]);

export const AUTH_OUTCOMES = z.enum(["SUCCESS", "FAILURE", "BLOCKED"]);

export const authEventSchema = z.object({
  id: z.string(),
  userId: z.string().nullable(),
  action: AUTH_ACTIONS,
  outcome: AUTH_OUTCOMES,
  reason: z.string().nullable(),
  identifier: z.string().nullable(),
  identifierKind: z.string().nullable(),
  method: z.string().nullable(),
  sessionId: z.string().nullable(),
  ipAddress: z.string().nullable(),
  userAgent: z.string().nullable(),
  country: z.string().nullable(),
  region: z.string().nullable(),
  city: z.string().nullable(),
  riskScore: z.number().int().nullable(),
  riskFactors: z.array(z.string()),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  createdAt: z.iso.datetime(),
});

export const adminEventSchema = z.object({
  id: z.string(),
  actorUserId: z.string(),
  actorEmail: z.string().nullable(),
  action: z.string(),
  targetType: z.string(),
  targetId: z.string(),
  targetLabel: z.string().nullable(),
  organizationId: z.string().nullable(),
  projectId: z.string().nullable(),
  environmentId: z.string().nullable(),
  before: z.record(z.string(), z.unknown()).nullable(),
  after: z.record(z.string(), z.unknown()).nullable(),
  ipAddress: z.string().nullable(),
  userAgent: z.string().nullable(),
  reason: z.string().nullable(),
  severity: AUDIT_SEVERITY,
  freshSession: z.boolean().nullable(),
  correlationId: z.string().nullable(),
  createdAt: z.iso.datetime(),
});
